export const HOME_FETCH_QUESTION_LIST_BEGIN = 'HOME_FETCH_QUESTION_LIST_BEGIN';
export const HOME_FETCH_QUESTION_LIST_SUCCESS =
  'HOME_FETCH_QUESTION_LIST_SUCCESS';
export const HOME_FETCH_QUESTION_LIST_FAILURE =
  'HOME_FETCH_QUESTION_LIST_FAILURE';
