export const HOME_FETCH_QUESTION_LIST_BEGIN = 'HOME_FETCH_QUESTION_LIST_BEGIN';
export const HOME_FETCH_QUESTION_LIST_SUCCESS =
  'HOME_FETCH_QUESTION_LIST_SUCCESS';
export const HOME_FETCH_QUESTION_LIST_FAILURE =
  'HOME_FETCH_QUESTION_LIST_FAILURE';

export const HOME_ADD_QUESTION_BEGIN = 'HOME_ADD_QUESTION_BEGIN';
export const HOME_ADD_QUESTION_SUCCESS = 'HOME_ADD_QUESTION_SUCCESS';
export const HOME_ADD_QUESTION_FAILURE = 'HOME_ADD_QUESTION_FAILURE';

export const HOME_RESET = 'HOME_RESET';
