export const AUTH_UPDATE_SIGNIN_BEGIN = 'AUTH_UPDATE_SIGNIN_BEGIN';
export const AUTH_UPDATE_SIGNIN_SUCCESS = 'AUTH_UPDATE_SIGNIN_SUCCESS';
export const AUTH_UPDATE_SIGNIN_FAILURE = 'AUTH_UPDATE_SIGNIN_FAILURE';

export const AUTH_SIGNUP_BEGIN = 'AUTH_SIGNUP_BEGIN';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAILURE = 'AUTH_SIGNUP_FAILURE';
export const AUTH_SIGNUP_MESSAGE_RESET = 'AUTH_SIGNUP_MESSAGE_RESET';

export const AUTH_SIGNIN_BEGIN = 'AUTH_SIGNIN_BEGIN';
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS';
export const AUTH_SIGNIN_FAILURE = 'AUTH_SIGNIN_FAILURE';
export const AUTH_SIGNIN_MESSAGE_RESET = 'AUTH_SIGNIN_MESSAGE_RESET';
