export const AUTH_UPDATE_SIGNIN_BEGIN = 'AUTH_UPDATE_SIGNIN_BEGIN';
export const AUTH_UPDATE_SIGNIN_SUCCESS = 'AUTH_UPDATE_SIGNIN_SUCCESS';
export const AUTH_UPDATE_SIGNIN_FAILURE = 'AUTH_UPDATE_SIGNIN_FAILURE';
