export const SEARCH_FETCH_RESULT_BEGIN = 'SEARCH_FETCH_RESULT_BEGIN';
export const SEARCH_FETCH_RESULT_SUCCESS = 'SEARCH_FETCH_RESULT_SUCCESS';
export const SEARCH_FETCH_RESULT_FAILURE = 'SEARCH_FETCH_RESULT_FAILURE';

export const SEARCH_RESET = 'SEARCH_RESET';
