export const MESSAGE_FETCH_CHAT_BEGIN = 'MESSAGE_FETCH_CHAT_BEGIN';
export const MESSAGE_FETCH_CHAT_SUCCESS = 'MESSAGE_FETCH_CHAT_SUCCESS';
export const MESSAGE_FETCH_CHAT_FAILURE = 'MESSAGE_FETCH_CHAT_FAILURE';

export const MESSAGE_FETCH_MESSAGE_BEGIN = 'MESSAGE_FETCH_MESSAGE_BEGIN';
export const MESSAGE_FETCH_MESSAGE_SUCCESS = 'MESSAGE_FETCH_MESSAGE_SUCCESS';
export const MESSAGE_FETCH_MESSAGE_FAILURE = 'MESSAGE_FETCH_MESSAGE_FAILURE';

export const MESSAGE_RESET = 'MESSAGE_RESET';
