export const QUESTION_FETCH_QUESTION_BEGIN = 'QUESTION_FETCH_QUESTION_BEGIN';
export const QUESTION_FETCH_QUESTION_SUCCESS =
  'QUESTION_FETCH_QUESTION_SUCCESS';
export const QUESTION_FETCH_QUESTION_FAILURE =
  'QUESTION_FETCH_QUESTION_FAILURE';

export const QUESTION_FETCH_QUESTION_COMMENT_BEGIN =
  'QUESTION_FETCH_QUESTION_COMMENT_BEGIN';
export const QUESTION_FETCH_QUESTION_COMMENT_SUCCESS =
  'QUESTION_FETCH_QUESTION_COMMENT_SUCCESS';
export const QUESTION_FETCH_QUESTION_COMMENT_FAILURE =
  'QUESTION_FETCH_QUESTION_COMMENT_FAILURE';

export const QUESTION_FETCH_ANSWER_BEGIN = 'QUESTION_FETCH_ANSWER_BEGIN';
export const QUESTION_FETCH_ANSWER_SUCCESS = 'QUESTION_FETCH_ANSWER_SUCCESS';
export const QUESTION_FETCH_ANSWER_FAILURE = 'QUESTION_FETCH_ANSWER_FAILURE';

export const QUESTION_FETCH_ANSWER_COMMENT_BEGIN =
  'QUESTION_FETCH_ANSWER_COMMENT_BEGIN';
export const QUESTION_FETCH_ANSWER_COMMENT_SUCCESS =
  'QUESTION_FETCH_ANSWER_COMMENT_SUCCESS';
export const QUESTION_FETCH_ANSWER_COMMENT_FAILURE =
  'QUESTION_FETCH_ANSWER_COMMENT_FAILURE';

export const QUESTION_FOLLOW_BEGIN = 'QUESTION_FOLLOW_BEGIN';
export const QUESTION_FOLLOW_SUCCESS = 'QUESTION_FOLLOW_SUCCESS';
export const QUESTION_FOLLOW_FAILURE = 'QUESTION_FOLLOW_FAILURE';

export const QUESTION_THUMBUP_BEGIN = 'QUESTION_THUMBUP_BEGIN';
export const QUESTION_THUMBUP_SUCCESS = 'QUESTION_THUMBUP_SUCCESS';
export const QUESTION_THUMBUP_FAILURE = 'QUESTION_THUMBUP_FAILURE';

export const QUESTION_ANSWER_UPVOTE_BEGIN = 'QUESTION_ANSWER_UPVOTE_BEGIN';
export const QUESTION_ANSWER_UPVOTE_SUCCESS = 'QUESTION_ANSWER_UPVOTE_SUCCESS';
export const QUESTION_ANSWER_UPVOTE_FAILURE = 'QUESTION_ANSWER_UPVOTE_FAILURE';

export const QUESTION_ANSWER_DOWNVOTE_BEGIN = 'QUESTION_ANSWER_DOWNVOTE_BEGIN';
export const QUESTION_ANSWER_DOWNVOTE_SUCCESS =
  'QUESTION_ANSWER_DOWNVOTE_SUCCESS';
export const QUESTION_ANSWER_DOWNVOTE_FAILURE =
  'QUESTION_ANSWER_DOWNVOTE_FAILURE';

export const QUESTION_ADD_ANSWER_BEGIN = 'QUESTION_ADD_ANSWER_BEGIN';
export const QUESTION_ADD_ANSWER_SUCCESS = 'QUESTION_ADD_ANSWER_SUCCESS';
export const QUESTION_ADD_ANSWER_FAILURE = 'QUESTION_ADD_ANSWER_FAILURE';

export const QUESTION_ADD_QUESTION_COMMENT_BEGIN =
  'QUESTION_ADD_QUESTION_COMMENT_BEGIN';
export const QUESTION_ADD_QUESTION_COMMENT_SUCCESS =
  'QUESTION_ADD_QUESTION_COMMENT_SUCCESS';
export const QUESTION_ADD_QUESTION_COMMENT_FAILURE =
  'QUESTION_ADD_QUESTION_COMMENT_FAILURE';

export const QUESTION_ADD_ANSWER_COMMENT_BEGIN =
  'QUESTION_ADD_ANSWER_COMMENT_BEGIN';
export const QUESTION_ADD_ANSWER_COMMENT_SUCCESS =
  'QUESTION_ADD_ANSWER_COMMENT_SUCCESS';
export const QUESTION_ADD_ANSWER_COMMENT_FAILURE =
  'QUESTION_ADD_ANSWER_COMMENT_FAILURE';

export const QUESTION_RESET = 'QUESTION_RESET';
