export const ACCOUNT_UPDATE_BEGIN = 'ACCOUNT_UPDATE_BEGIN';
export const ACCOUNT_UPDATE_SUCCESS = 'ACCOUNT_UPDATE_SUCCESS';
export const ACCOUNT_UPDATE_FAILURE = 'ACCOUNT_UPDATE_FAILURE';

export const ACCOUNT_UPDATE_AVATAR_BEGIN = 'ACCOUNT_UPDATE_AVATAR_BEGIN';
export const ACCOUNT_UPDATE_AVATAR_SUCCESS = 'ACCOUNT_UPDATE_AVATAR_SUCCESS';
export const ACCOUNT_UPDATE_AVATAR_FAILURE = 'ACCOUNT_UPDATE_AVATAR_FAILURE';

export const ACCOUNT_RESET = 'ACCOUNT_RESET';
