export const PROFILE_FETCH_ITEM_BEGIN = 'PROFILE_FETCH_ITEM_BEGIN';
export const PROFILE_FETCH_ITEM_SUCCESS = 'PROFILE_FETCH_ITEM_SUCCESS';
export const PROFILE_FETCH_ITEM_FAILURE = 'PROFILE_FETCH_ITEM_FAILURE';

export const PROFILE_FETCH_USER_BEGIN = 'PROFILE_FETCH_USER_BEGIN';
export const PROFILE_FETCH_USER_SUCCESS = 'PROFILE_FETCH_USER_SUCCESS';
export const PROFILE_FETCH_USER_FAILURE = 'PROFILE_FETCH_USER_FAILURE';

export const PROFILE_FETCH_USER_INFO_BEGIN = 'PROFILE_FETCH_USER_INFO_BEGIN';
export const PROFILE_FETCH_USER_INFO_SUCCESS =
  'PROFILE_FETCH_USER_INFO_SUCCESS';
export const PROFILE_FETCH_USER_INFO_FAILURE =
  'PROFILE_FETCH_USER_INFO_FAILURE';

export const PROFILE_FOLLOW_USER_BEGIN = 'PROFILE_FOLLOW_USER_BEGIN';
export const PROFILE_FOLLOW_USER_SUCCESS = 'PROFILE_FOLLOW_USER_SUCCESS';
export const PROFILE_FOLLOW_USER_FAILURE = 'PROFILE_FOLLOW_USER_FAILURE';

export const PROFILE_ITEM_RESET = 'PROFILE_ITEM_RESET';
export const PROFILE_RESET = 'PROFILE_RESET';
