export const ANSWER_FETCH_QUESTION_BEGIN = 'ANSWER_FETCH_QUESTION_BEGIN';
export const ANSWER_FETCH_QUESTION_SUCCESS = 'ANSWER_FETCH_QUESTION_SUCCESS';
export const ANSWER_FETCH_QUESTION_FAILURE = 'ANSWER_FETCH_QUESTION_FAILURE';

export const ANSWER_RESET = 'ANSWER_RESET';
