export const FEED_FETCH_FEED_BEGIN = 'FEED_FETCH_FEED_BEGIN';
export const FEED_FETCH_FEED_SUCCESS = 'FEED_FETCH_FEED_SUCCESS';
export const FEED_FETCH_FEED_FAILURE = 'FEED_FETCH_FEED_FAILURE';

export const FEED_RESET = 'FEED_RESET';
